// Generated by EmDash CLI
// Do not edit manually - run `emdash types` to regenerate

import type { PortableTextBlock } from "emdash";

export interface FundingProgram {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  eyebrow?: string;
  h1?: string;
  direct_answer?: string;
  verified?: string;
  source_url?: string;
  source_label?: string;
  facts?: unknown;
  sections?: unknown;
  faq?: unknown;
  related_links?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Industry {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  eyebrow?: string;
  h1?: string;
  hero_lead?: string;
  funding_text?: string;
  direct_answer?: string;
  differences_title?: string;
  differences?: unknown;
  pillars?: unknown;
  faq?: unknown;
  cta_title?: string;
  cta_lead?: string;
  card_title?: string;
  card_body?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface ManagedItService {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  hero?: unknown;
  sections?: unknown;
  cta?: unknown;
  callout?: string;
  schema?: unknown;
  breadcrumb?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  hero?: unknown;
  sections?: unknown;
  cta?: unknown;
  schema?: unknown;
  breadcrumb?: unknown;
  callout?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}
